# Generated by Django 4.0.3 on 2022-03-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0002_remove_project_allow_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bug', 'bug'), ('Task', 'task'), ('req', 'request'), ('oth', 'other')], default='Task', max_length=10)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('TD', 'Todo'), ('IP', 'In Progress'), ('RES', 'Resolved'), ('CLS', 'Close')], default='TD', max_length=10)),
                ('priority', models.CharField(choices=[('NORM', 'Normal'), ('HG', 'High'), ('LW', 'Low'), ('IMM', 'Immediate')], default='NORM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_hours', models.IntegerField(blank=True, null=True)),
                ('act_hours', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('accountable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountable_tickets', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(to='tickets.ticketfiles')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone', to='tracker.milestone')),
            ],
        ),
    ]
