# Generated by Django 4.0.3 on 2022-03-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_project_allow_milestone'),
        ('tickets', '0002_rename_type_ticket__type_ticket_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='key',
            field=models.CharField(default='PMS-1000', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tracker.project'),
            preserve_default=False,
        ),
    ]
