# Generated by Django 4.0.3 on 2022-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_key_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='_type',
            field=models.CharField(choices=[('BUG', 'bug'), ('TASK', 'task'), ('REQUEST', 'request'), ('OTHER', 'other')], default='TASK', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low'), ('Immediate', 'Immediate')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Close')], default='Todo', max_length=50),
        ),
    ]
