# Generated by Django 4.0.3 on 2022-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket__type_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='files',
            field=models.ManyToManyField(blank=True, to='tickets.ticketfiles'),
        ),
    ]
