# Generated by Django 4.0.3 on 2022-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
