# Generated by Django 4.0.3 on 2022-03-27 16:27

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
