# Generated by Django 4.0.3 on 2022-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='key',
            field=models.CharField(blank=True, default='PMS-1000', max_length=100, null=True),
        ),
    ]
