# Generated by Django 4.0.3 on 2022-03-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='_type',
            new_name='ticket_type',
        ),
    ]
