# Generated by Django 4.0.3 on 2022-03-30 18:17

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(default='something only'),
            preserve_default=False,
        ),
    ]
