# Generated by Django 4.0.3 on 2022-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',field=models.TextField(),            
            preserve_default=False,
        ),
    ]
