# Generated by Django 4.0.3 on 2022-03-30 19:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=django_quill.fields.QuillField(default='some description'),
        ),
    ]
