# Generated by Django 4.0.3 on 2022-04-02 14:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=django_quill.fields.QuillField(blank=True, default='some description', null=True),
        ),
    ]
