# Generated by Django 4.0.3 on 2022-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='hist_type',
            field=models.CharField(choices=[(1, 'update'), (2, 'new_ticket')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
