# Generated by Django 4.0.3 on 2022-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_tickethistory_hist_type_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='updated',
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
