# Generated by Django 4.0.3 on 2022-04-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_tickethistory_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ('-created_on',)},
        ),
    ]
