# Generated by Django 4.0.3 on 2022-04-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='admin',
        ),
    ]
