# Generated by Django 4.0.3 on 2022-03-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Allow_Milestone',
        ),
    ]
