# Generated by Django 4.0.3 on 2022-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'project Manager'), ('3', 'Developer')], default='3', max_length=30),
        ),
    ]
