# Generated by Django 4.0.3 on 2022-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_project_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_site_administrator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
        ),
    ]
