# Generated by Django 4.0.3 on 2022-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'project Manager'), ('3', 'Developer')], default='3', max_length=100),
        ),
    ]
